### PR TITLE
repository setup

### PR DESCRIPTION
**Pull request by MessaoudAzidane**
### Description
Setup the repository:
- The repo is an `express` app
- We have mainly three endpoints:
       * `/swap`
       * `/add_liquidity`
       * `/remove_liquidity`

### CODE REVIEW

**Review by specialistvlad — COMMENTED** [review]
LGTM

**Review by DevAseel — APPROVED** [review]
Awesome!

**Review by mrrfid — APPROVED** [review]
Looks very complete.

**Review by russell-mccullin — COMMENTED** [review]
No issues found.

**Pull request merged**
